apiVersion: v1
kind: ConfigMap
metadata:
  name: flightaware-env-file
  namespace: flightaware
data:
  TZ: {{ .Values.tz }}
  LAT: {{ .Values.lat }}
  LONG: {{ .Values.long }}
  FEEDER_ID: {{ .Values.piaware.feeder_id }}
  RECEIVER_TYPE: {{ .Values.receiver_type }}
