apiVersion: v1
kind: ConfigMap
metadata:
  name: flightaware-env-file
  namespace: flightaware
data:
  TZ: "America/New_York"
  LAT: "36.7134572"
  LONG: "-76.2757609"
  FEEDER_ID: 8921d173-bdaf-4b2a-a616-5bb6505cb778
  RECEIVER_TYPE: rtlsdr
