apiVersion: v1
kind: Service
metadata:
  name: http-nodeport
  namespace: flightaware
spec:
  ports:
  - name: http
    nodePort: 30591
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: prom
    nodePort: 30592
    port: 9105
    protocol: TCP
    targetPort: 9105
  selector:
    app: apps.deployment-flightaware-piaware
  sessionAffinity: None
  type: NodePort
